export enum AssignmentSection {
  BIBLE_READING = "BIBLE_READING",
  APPLY_YOURSELF = "APPLY_YOURSELF",
}

export enum AssignmentType {
  BIBLE_READING = "BIBLE_READING",
  START_CONVERSATION = "START_CONVERSATION",
  MAKE_RETURN_VISIT = "MAKE_RETURN_VISIT",
  BIBLE_STUDY = "BIBLE_STUDY",
  EXPLAIN_BELIEFS = "EXPLAIN_BELIEFS",
  MAKE_DISCIPLES = "MAKE_DISCIPLES",
  TALK = "TALK",
  OTHER = "OTHER",
}

export enum Room {
  MAIN = "MAIN",
  AUXILIARY = "AUXILIARY",
}

export enum AssignmentStatus {
  PENDING = "PENDING",
  NOTIFIED = "NOTIFIED",
  CANCELLED = "CANCELLED",
  COMPLETED = "COMPLETED",
}

export enum ReminderType {
  INITIAL_NOTICE = "INITIAL_NOTICE",
  SEVEN_DAYS_BEFORE = "SEVEN_DAYS_BEFORE",
  THREE_DAYS_BEFORE = "THREE_DAYS_BEFORE",
  ONE_DAY_BEFORE = "ONE_DAY_BEFORE",
  SAME_DAY = "SAME_DAY",
  CHANGE_NOTICE = "CHANGE_NOTICE",
  CANCELLATION_NOTICE = "CANCELLATION_NOTICE",
}

export enum ReminderStatus {
  PENDING = "PENDING",
  SENT = "SENT",
  FAILED = "FAILED",
  SKIPPED = "SKIPPED",
  CANCELLED = "CANCELLED",
}

export enum MessageLogStatus {
  SENT = "SENT",
  FAILED = "FAILED",
  SKIPPED = "SKIPPED",
}

export enum WhatsappSessionStatus {
  STARTING = "STARTING",
  QR_REQUIRED = "QR_REQUIRED",
  AUTHENTICATED = "AUTHENTICATED",
  READY = "READY",
  DISCONNECTED = "DISCONNECTED",
  FAILED = "FAILED",
}
