export enum Gender {
  MALE = "MALE",
  FEMALE = "FEMALE",
}


export enum AssignmentSection {
  BIBLE_READING = "BIBLE_READING",
  APPLY_YOURSELF = "APPLY_YOURSELF",
  // Fase 3: resto de la reunión.
  OPENING = "OPENING",
  TREASURES = "TREASURES",
  LIVING_AS_CHRISTIANS = "LIVING_AS_CHRISTIANS",
  CONCLUSION = "CONCLUSION",
}

export enum AssignmentType {
  BIBLE_READING = "BIBLE_READING",
  START_CONVERSATION = "START_CONVERSATION",
  MAKE_RETURN_VISIT = "MAKE_RETURN_VISIT",
  BIBLE_STUDY = "BIBLE_STUDY",
  EXPLAIN_BELIEFS = "EXPLAIN_BELIEFS",
  MAKE_DISCIPLES = "MAKE_DISCIPLES",
  TALK = "TALK",
  AUDIENCE_ANALYSIS = "AUDIENCE_ANALYSIS",
  OTHER = "OTHER",
  // Fase 3: resto de la reunión (aditivo, no altera SMM).
  CHAIRMAN = "CHAIRMAN",
  OPENING_COMMENTS = "OPENING_COMMENTS",
  OPENING_PRAYER = "OPENING_PRAYER",
  TREASURES_TALK = "TREASURES_TALK",
  SPIRITUAL_GEMS = "SPIRITUAL_GEMS",
  CHRISTIAN_LIVING = "CHRISTIAN_LIVING",
  CONGREGATION_BIBLE_STUDY_CONDUCTOR = "CONGREGATION_BIBLE_STUDY_CONDUCTOR",
  CONGREGATION_BIBLE_STUDY_READER = "CONGREGATION_BIBLE_STUDY_READER",
  CONCLUDING_COMMENTS = "CONCLUDING_COMMENTS",
  CLOSING_PRAYER = "CLOSING_PRAYER",
  SONG = "SONG",
}

export enum Room {
  MAIN = "MAIN",
  AUXILIARY = "AUXILIARY",
}

export enum AssignmentStatus {
  DRAFT = "DRAFT",
  SCHEDULED = "SCHEDULED",
  COMPLETED = "COMPLETED",
  CANCELLED = "CANCELLED",
}

export enum ReminderType {
  INITIAL_NOTICE = "INITIAL_NOTICE",
  SEVEN_DAYS_BEFORE = "SEVEN_DAYS_BEFORE",
  THREE_DAYS_BEFORE = "THREE_DAYS_BEFORE",
  ONE_DAY_BEFORE = "ONE_DAY_BEFORE",
  SAME_DAY = "SAME_DAY",
  CHANGE_NOTICE = "CHANGE_NOTICE",
  CANCELLATION_NOTICE = "CANCELLATION_NOTICE",
}

export enum ReminderStatus {
  PENDING = "PENDING",
  QUEUED = "QUEUED",
  SENDING = "SENDING",
  SENT = "SENT",
  FAILED = "FAILED",
  SKIPPED = "SKIPPED",
  CANCELLED = "CANCELLED",
  DEAD = "DEAD",
}

export enum MessageLogStatus {
  SENT = "SENT",
  FAILED = "FAILED",
  SKIPPED = "SKIPPED",
}

export enum WhatsappSessionStatus {
  STARTING = "STARTING",
  QR_REQUIRED = "QR_REQUIRED",
  AUTHENTICATED = "AUTHENTICATED",
  READY = "READY",
  DISCONNECTED = "DISCONNECTED",
  FAILED = "FAILED",
}

export enum MonthlyScheduleStatus {
  DRAFT = "DRAFT",
  ACTIVE = "ACTIVE",
  ARCHIVED = "ARCHIVED",
  CANCELLED = "CANCELLED",
}

export enum MeetingWeekStatus {
  DRAFT = "DRAFT",
  READY = "READY",
  ACTIVE = "ACTIVE",
  COMPLETED = "COMPLETED",
  ARCHIVED = "ARCHIVED",
  CANCELLED = "CANCELLED",
}

export enum AutomationPlanStatus {
  DRAFT = "DRAFT",
  ACTIVE = "ACTIVE",
  SUPERSEDED = "SUPERSEDED",
  CANCELLED = "CANCELLED",
  ARCHIVED = "ARCHIVED",
}

export enum ReminderRecipientRole {
  ASSIGNED = "ASSIGNED",
  COMPANION = "COMPANION",
}
